SELECT DISTINCT CITY FROM STATION
WHERE NOT (CITY LIKE 'A%' or CITY LIKE 'E%' or CITY LIKE 'I%' or CITY LIKE 'O%' or  CITY LIKE 'U%') or NOT (CITY LIKE '%a' or CITY LIKE '%e' or CITY LIKE '%i' or CITY LIKE '%o' OR  CITY LIKE '%u');
